import { Slider, VerticalBox, HorizontalBox } from "std-widgets.slint";

export component MainWindow inherits Window {
    title: "Camera";
    preferred-width: 900px;
    preferred-height: 600px;

    in-out property <image> camera-frame;
    in-out property <image> target-frame;

    HorizontalBox {
        padding: 10px;

        Image {
            source: camera-frame;
            image-fit: contain;
        }

        Image {
            source: target-frame;
            image-fit: contain;
        }
    }
}