import {
    Slider,
    VerticalBox,
    HorizontalBox,
    GroupBox,
} from "std-widgets.slint";
import { CameraFeed } from "CameraFeed.slint";



export component MainWindow inherits Window {
    title: "Camera";
    preferred-width: 900px;
    preferred-height: 600px;

    in-out property <image> camera-frame;
    in-out property <image> target-frame;
    in property <bool> camera-zoom-supported;

    HorizontalBox {
        padding: 10px;

        VerticalBox {

            CameraFeed {
                camera-frame: camera-frame;
                vertical-stretch: 1;
            }

            GroupBox {
                title: "Zoom";
                vertical-stretch: 0;
                Slider {
                    minimum: 1;
                    maximum: 20;
                    value: 9;
                    enabled: camera-zoom-supported;
                }
            }
        }

        Image {
            source: camera-frame;
            image-fit: contain;
        }
    }
}
